# Generated by Django 4.1.5 on 2023-01-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='hash_url',
        ),
        migrations.AddField(
            model_name='url',
            name='short_url',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='life_time_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
